import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";
import ShoppingContextProvider from "@/context/shopingContext";



export const metadata: Metadata = {
    title: "Next Shop",
    description: "Generated by Mahan",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className='rtl'>
        <body>
        <ShoppingContextProvider>
            <Layout>{children}</Layout>
        </ShoppingContextProvider>
        </body>
        </html>
    );
}
